### ISSUE TITLE
Invalid existing rewind buffer

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/sm-archiver#11]
At start when some rewind don't has buffer look like waveform crash:

```
/srv/sm-archiver/node_modules/waveform-data/lib/core.js:153
      throw new RangeError("We can't end prior to the starting point [" + Number(end) + " <= " + Number(start) + "]");
      ^

RangeError: We can't end prior to the starting point [0 <= 0]
    at Object.WaveformData.offset (/srv/sm-archiver/node_modules/waveform-data/lib/core.js:153:13)
    at Object.WaveformData (/srv/sm-archiver/node_modules/waveform-data/lib/core.js:72:8)
    at Function.createFromResponseData [as create] (/srv/sm-archiver/node_modules/waveform-data/lib/core.js:117:10)
    at WaveTransform.<anonymous> (/srv/sm-archiver/js/src/archiver/stream_archiver.js:46:39)
    at emitNone (events.js:67:13)
    at WaveTransform.emit (events.js:166:7)
    at emitReadable_ (_stream_readable.js:419:10)
    at emitReadable (_stream_readable.js:413:7)
    at readableAddChunk (_stream_readable.js:164:13)
    at WaveTransform.Readable.push (_stream_readable.js:111:10)
    at WaveTransform.Transform.push (_stream_transform.js:128:32)
    at /srv/sm-archiver/js/src/wave_transform.js:38:15
    at /srv/sm-archiver/node_modules/underscore/underscore.js:890:21
    at WaveformStream.<anonymous> (/srv/sm-archiver/node_modules/sm-waveform/js/waveform.js:54:18)
    at WaveformStream.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

In this case one of the radios, has 1 sec buffer_length (to check this value go to "host.com/api/streams"):

```
{
    "key": "radio.mp3",
    "id": "radio.mp3",
    "vitals": {
        "streamKey": "mp3-44100-32-m",
        "framesPerSec": 38.28125,
        "emitDuration": 0.5
    },
    "source": {
        "key": "radio.mp3",
        "sources": [{
            "source": "Proxy (http://server.com/radio.mp3)",
            "connected": true,
            "url": "http://server.com/radio.mp3",
            "streamKey": "mp3-44100-32-m",
            "uuid": "d5c1772f-98b6-4354-9c36-ab68166b239b",
            "isFallback": true,
            "last_ts": "2016-06-04T02:53:54.175Z",
            "connected_at": "2016-06-04T04:03:56.217Z"
        }]
    },
    "rewind": {
        "buffer_length": 1,
        "first_buffer_ts": "2016-06-04T02:53:54.175Z",
        "last_buffer_ts": "2016-06-04T02:53:54.175Z",
        "hls_segments": 1440,
        "hls_first_seg_id": 38461,
        "hls_first_seg_ts": "2016-06-03T22:26:50.000Z",
        "hls_last_seg_id": 39900,
        "hls_last_seg_ts": "2016-06-04T02:26:40.000Z"
    }
}
```

**Comment by cdgraff** [comment]
fixed
