### ISSUE TITLE
TypeError: Cannot read property 'ts' of undefined

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/sm-archiver#13]
After run for long time and upload all the segments, to S3, start to Expiring Segments, and got this error:

```
sm:archiver:stream Expiring segment 11727 from waveform cache +0ms
/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/rewind/memory_store.js:43
        db = Math.abs(b.ts - ts);
                       ^

TypeError: Cannot read property 'ts' of undefined
    at MemoryStore.module.exports.MemoryStore._findTimestampOffset (/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/rewind/memory_store.js:43:24)
    at MemoryStore.module.exports.MemoryStore.range (/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/rewind/memory_store.js:73:21)
    at SegmentPuller.module.exports.SegmentPuller._transform (/srv/sm-archiver/js/src/segment_puller.js:20:33)
    at SegmentPuller.Transform._read (_stream_transform.js:167:10)
    at SegmentPuller.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at SegmentPuller.Writable.write (_stream_writable.js:214:11)
    at Stream.<anonymous> (/srv/sm-archiver/js/src/archiver/stream_archiver.js:87:30)
    at emitOne (events.js:82:20)
    at Stream.emit (events.js:169:7)
    at SocketSource.<anonymous> (/srv/sm-archiver/js/src/archiver/stream_archiver.js:56:29)
    at emitOne (events.js:82:20)
    at SocketSource.emit (events.js:169:7)
    at SlaveIO.<anonymous> (/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/slave/socket_source.js:25:22)
    at emitOne (events.js:77:13)
    at SlaveIO.emit (events.js:169:7)
```

**Comment by martindido** [comment]
@cdgraff is this still happening?

**Comment by cdgraff** [comment]
fixed!
