### ISSUE TITLE
Deprecation error trying to play m3u8 live

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/sm-archiver#27]
When try to play this url:

[http://c3-logger-archiver-01.mediainbox.net:8000/cadena3.mp3.m3u8](url)

Got this error:

```
0|prod-c3- | Fri, 23 Sep 2016 05:24:57 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at node_modules/streammachine/js/src/streammachine/outputs/base.js:24:49
0|prod-c3- | Fri, 23 Sep 2016 05:24:57 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at node_modules/streammachine/js/src/streammachine/outputs/base.js:27:192
0|prod-c3- | Fri, 23 Sep 2016 05:24:57 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at node_modules/streammachine/js/src/streammachine/outputs/live_streaming.js:87:25
```

**Comment by martindido** [comment]
Not really a bug from the archiver but one of the slave underneath it.

Solved at: https://github.com/mediainbox/StreamMachine/pull/15

**Comment by martindido** [comment]
Really solved at: https://github.com/mediainbox/StreamMachine/pull/17
