### ISSUE TITLE
Starting fail when try to archive failure source

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/sm-archiver#34]
c3mendoza.mp3 is into master configuration, but is not connected any source for this reason don't have any segment, after restart we got this error, and application fail.

```
0|prod-c3- | Sat, 01 Oct 2016 22:40:48 GMT sm:archiver:transformers:waveform Segment 1475254421024 from c3mendoza.mp3
0|prod-c3- | Sat, 01 Oct 2016 22:40:48 GMT sm:archiver:stream Segment 1475361171871 archived
0|prod-c3- | Sat, 01 Oct 2016 22:40:48 GMT sm:archiver:transformers:s3 Segment 1475361181856 from fmcordoba.aac
0|prod-c3- | TypeError: Cannot read property 'segments' of null
0|prod-c3- |     at /srv/sm-archiver/js/src/archiver/stream.js:88:97
0|prod-c3- |     at Socket.<anonymous> (/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/slave/slave_io.js:182:16)
0|prod-c3- |     at Socket.onack (/srv/sm-archiver/node_modules/socket.io-client/lib/socket.js:295:6)
0|prod-c3- |     at Socket.onpacket (/srv/sm-archiver/node_modules/socket.io-client/lib/socket.js:220:12)
0|prod-c3- |     at Manager.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
0|prod-c3- |     at Manager.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
0|prod-c3- |     at Manager.ondecoded (/srv/sm-archiver/node_modules/socket.io-client/lib/manager.js:301:8)
0|prod-c3- |     at Decoder.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
0|prod-c3- |     at Decoder.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
0|prod-c3- |     at Decoder.add (/srv/sm-archiver/node_modules/socket.io-parser/index.js:247:12)
0|prod-c3- |     at Manager.ondata (/srv/sm-archiver/node_modules/socket.io-client/lib/manager.js:291:16)
0|prod-c3- |     at Socket.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
0|prod-c3- |     at Socket.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
0|prod-c3- |     at Socket.onPacket (/srv/sm-archiver/node_modules/engine.io-client/lib/socket.js:430:14)
0|prod-c3- |     at WS.<anonymous> (/srv/sm-archiver/node_modules/engine.io-client/lib/socket.js:248:10)
0|prod-c3- |     at WS.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
0|prod-c3- | adding Console transport
```

**Comment by cdgraff** [comment]
Now I saw this error is similar but dont the same line:

```
debug: Rewind's max buffer length is max=1800, secsPerChunk=0.5, secs=0.5, stream=c3mendoza-dev.mp3
at Socket.<anonymous> (/srv/sm-archiver/node_modules/streammachine/js/src/streammachine/slave/slave_io.js:182:16)
at /srv/sm-archiver/js/src/archiver/stream.js:95:97
Wed, 21 Jun 2017 01:50:47 GMT sm:archiver:runner TypeError: Cannot read property 'segments' of null
at Socket.onack (/srv/sm-archiver/node_modules/socket.io-client/lib/socket.js:295:6)
at Socket.onpacket (/srv/sm-archiver/node_modules/socket.io-client/lib/socket.js:220:12)
at Manager.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
at Manager.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
at Manager.ondecoded (/srv/sm-archiver/node_modules/socket.io-client/lib/manager.js:301:8)
at Decoder.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
at WS.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
at Decoder.add (/srv/sm-archiver/node_modules/socket.io-parser/index.js:247:12)
at Manager.ondata (/srv/sm-archiver/node_modules/socket.io-client/lib/manager.js:291:16)
at Socket.<anonymous> (/srv/sm-archiver/node_modules/component-bind/index.js:21:15)
at Socket.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)
at Socket.onPacket (/srv/sm-archiver/node_modules/engine.io-client/lib/socket.js:430:14)
at WS.<anonymous> (/srv/sm-archiver/node_modules/engine.io-client/lib/socket.js:248:10)
at Decoder.Emitter.emit (/srv/sm-archiver/node_modules/component-emitter/index.js:134:20)

```

**Comment by martindido** [comment]
@cdgraff check it now, should be fixed finally
