### ISSUE TITLE
Archiver fails when not enough Segments in a Stream

### ISSUE THREAD

**Issue by martindido** [mediainbox/sm-archiver#6]
When a Stream has less than a certain amount of segments, after starting Archiver, it runs for a few seconds and then it fails with this error:

```
/data/node_modules/waveform-data/lib/core.js:337
      throw new Error("Zoom level "+samples_per_pixel+" too low, minimum: "+scale);
      ^

Error: Zoom level 590 too low, minimum: 2205
    at Object.WaveformData.resample (/data/node_modules/waveform-data/lib/core.js:337:13)
    at StreamArchiver.module.exports.Archiver.StreamArchiver.StreamArchiver._updatePreview (/data/js/src/archiver.js:176:71)
    at Debounce.cb (/data/js/src/archiver.js:88:24)
    at null._onTimeout (/data/node_modules/streammachine/js/src/streammachine/util/debounce.js:21:24)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by martindido** [comment]
Happening with stream "mitrecordoba" at the moment.
